# Generated by Django 4.2.7 on 2024-01-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(default='None', max_length=250)),
                ('phone', models.IntegerField(default=None)),
                ('id', models.AutoField(default='2024-01-01', primary_key=True, serialize=False)),
                ('designation', models.CharField(default=None, max_length=449)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(default='None', max_length=250)),
                ('image1', models.URLField(default='None')),
                ('image2', models.URLField(default='None')),
                ('image3', models.URLField(default='None')),
                ('poster', models.URLField(default='None')),
                ('para1', models.CharField(default='None', max_length=1000)),
                ('para2', models.CharField(default='None', max_length=1000)),
                ('para3', models.CharField(default='None', max_length=1000)),
                ('para4', models.CharField(default='None', max_length=1000)),
                ('para5', models.CharField(default='None', max_length=1000)),
                ('para6', models.CharField(default='None', max_length=1000)),
                ('date', models.DateField(default='2024-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_video_title', models.CharField(default='None', max_length=250)),
                ('latest_video_thumbnail', models.URLField(default='None')),
                ('latest_video', models.URLField(default='None')),
                ('magical_video_title', models.CharField(default='None', max_length=250)),
                ('magical_video_thumbnail', models.URLField(default='None')),
                ('magical_video', models.URLField(default='None')),
                ('great_video_title', models.CharField(default='None', max_length=250)),
                ('great_video_thumbnail', models.URLField(default='None')),
                ('great_video', models.URLField(default='None')),
                ('highlight_video_title', models.CharField(default='None', max_length=250)),
                ('highlight_video_thumbnail', models.URLField(default='None')),
                ('highlight_video', models.URLField(default='None')),
                ('enjoyable_video_title', models.CharField(default='None', max_length=250)),
                ('enjoyable_video_thumbnail', models.URLField(default='None')),
                ('enjoyable_video', models.URLField(default='None')),
                ('video_date', models.DateField(default='2024-01-01')),
            ],
        ),
    ]
