# Generated by Django 4.2.7 on 2024-01-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketlive', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=250)),
                ('phone', models.IntegerField(default=None)),
                ('sallary', models.IntegerField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
