# Generated by Django 4.2.7 on 2024-01-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketlive', '0006_alter_video_thumbnail_alter_video_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('image1', models.URLField(blank=True)),
                ('image2', models.URLField(blank=True)),
                ('image3', models.URLField(blank=True)),
                ('poster', models.URLField(blank=True)),
                ('para1', models.TextField(blank=True)),
                ('para2', models.TextField(blank=True)),
                ('para3', models.TextField(blank=True)),
                ('para4', models.TextField(blank=True)),
                ('para5', models.TextField(blank=True)),
                ('para6', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
