# Generated by Django 4.2.7 on 2024-01-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketlive', '0008_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='video_date',
            field=models.DateField(blank=True),
        ),
    ]
